### ISSUE TITLE
org.apache.hc.core5.http.NoHttpResponseException: localhost:2375 failed to respond

### ISSUE THREAD

**Issue by cmoulliard** [snowdrop/java-buildpack-client#60] opened 2024-05-27 11:36 UTC
## Issue

When we execute `./pack.java` within the `samples/hello-quarkus`, we got this error
```
[main] INFO dev.snowdrop.buildpack.lifecycle.LifecyclePhaseFactory - - mounted /var/run/docker.sock at /var/run/docker.sock
[main] INFO dev.snowdrop.buildpack.lifecycle.LifecyclePhaseFactory - - mounted buildpack-output-qehdanxvwx at /layers
[main] INFO dev.snowdrop.buildpack.lifecycle.LifecyclePhaseFactory - - container id 3619cb8b340e26f66223169034641611c912d0f549a74d354d130cd6b09cee64
[main] INFO dev.snowdrop.buildpack.lifecycle.LifecyclePhaseFactory - - image reference 831c5292e451cf401acecb2e1e661e4d2f94c661da503c7a0b4d3a728169f993
[main] INFO dev.snowdrop.buildpack.lifecycle.phases.Restorer - - restorer container id 3619cb8b340e26f66223169034641611c912d0f549a74d354d130cd6b09cee64 will be run with uid 1002 and args [/cnb/lifecycle/restorer, -uid, 1002, -gid, 1000, -layers, /layers, -cache-dir, /cache-dir, -log-level, debug, -build-image, paketocommunity/builder-ubi-base:latest]
- restorer container id 3619cb8b340e26f66223169034641611c912d0f549a74d354d130cd6b09cee64 will be run with uid 1002 and args [/cnb/lifecycle/restorer, -uid, 1002, -gid, 1000, -layers, /layers, -cache-dir, /cache-dir, -log-level, debug, -build-image, paketocommunity/builder-ubi-base:latest]
[main] INFO dev.snowdrop.buildpack.lifecycle.phases.Restorer - - launching restorer container
[main] INFO dev.snowdrop.buildpack.lifecycle.phases.Restorer - - attaching log relay
[docker-java-stream--1039344372] ERROR com.github.dockerjava.api.async.ResultCallbackTemplate - Error during callback
java.lang.RuntimeException: org.apache.hc.core5.http.NoHttpResponseException: localhost:2375 failed to respond
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:195)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClient.execute(ApacheDockerHttpClient.java:9)
        at com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:228)
        at com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
        at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: org.apache.hc.core5.http.NoHttpResponseException: localhost:2375 failed to respond
        at org.apache.hc.core5.http.impl.io.DefaultHttpResponseParser.createConnectionClosedException(DefaultHttpResponseParser.java:87)
        at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:243)
        at org.apache.hc.core5.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:53)
        at org.apache.hc.core5.http.impl.io.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:187)
        at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:175)
        at com.github.dockerjava.httpclient5.HijackingHttpRequestExecutor.execute(HijackingHttpRequestExecutor.java:50)
        at org.apache.hc.core5.http.impl.io.HttpRequestExecutor.execute(HttpRequestExecutor.java:218)
        at org.apache.hc.client5.http.impl.io.PoolingHttpClientConnectionManager$InternalConnectionEndpoint.execute(PoolingHttpClientConnectionManager.java:596)
        at org.apache.hc.client5.http.impl.classic.InternalExecRuntime.execute(InternalExecRuntime.java:215)
        at org.apache.hc.client5.http.impl.classic.MainClientExec.execute(MainClientExec.java:107)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ConnectExec.execute(ConnectExec.java:181)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ProtocolExec.execute(ProtocolExec.java:172)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.HttpRequestRetryExec.execute(HttpRequestRetryExec.java:93)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.ContentCompressionExec.execute(ContentCompressionExec.java:128)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement$1.proceed(ExecChainElement.java:57)
        at org.apache.hc.client5.http.impl.classic.RedirectExec.execute(RedirectExec.java:116)
        at org.apache.hc.client5.http.impl.classic.ExecChainElement.execute(ExecChainElement.java:51)
        at org.apache.hc.client5.http.impl.classic.InternalHttpClient.doExecute(InternalHttpClient.java:178)
        at org.apache.hc.client5.http.impl.classic.CloseableHttpClient.execute(CloseableHttpClient.java:67)
        at com.github.dockerjava.httpclient5.ApacheDockerHttpClientImpl.execute(ApacheDockerHttpClientImpl.java:191)
        ... 4 more
```

If I re-execute the command `./pack.java`, then error is gone. Really strange !!

Useful information
```
Branch/PR: `platform-12`
Java JDK: 17.0.11
Podman: 5.0.2 rootful
```

@BarDweller

**Comment by BarDweller** [comment] 2024-06-10 16:03
@cmoulliard  I'm unable to recreate this, and I haven't seen the integration tests report this either

The stack trace indicates that localhost:2375 doesn't answer.. 

That isn't a host/port configured in the quarkus-sample, but it is a port normally used by docker when communicating via tcp, have you altered pack.java locally? what configuration are you attempting to build with? (eg, DOCKER_HOST value, podman/docker version)

The log above indicates it's mounting in /var/run/docker.sock (expected as the destination image doesn't contain a registry reference).. so it's unclear why the container would be choosing to use tcp via localhost:2375 .. It's getting all the way through the restorer phase too, which is a fair way thru the build, yet I'm guessing this error didn't occur before that, which is odd, as there's nothing special about restorer that would cause it to access the daemon differently.. 

If this is repeatable for you, it might be interesting to capture more trace to figure out what the root cause is.

**Comment by cmoulliard** [comment] 2024-06-11 09:03
> That isn't a host/port configured in the quarkus-sample, but it is a port normally used by docker when communicating via tcp, have you altered pack.java locally? what configuration are you attempting to build with? (eg, DOCKER_HOST value, podman/docker version)

This issue occurs from time to time. I got it the first time I executed `./pack.java` with the Quarkus hello sample, podman `5.0.3` and `DOCKER_HOST="unix:///var/run/docker.sock"` but not the second time :-(

Nevertheless, end of the build using podman, I got this error
```
2024-06-11T11:00:14+02:00       [INFO] Compiling 2 source files with javac [debug target 1.8] to target/classes
2024-06-11T11:00:15+02:00       [INFO] -------------------------------------------------------------
2024-06-11T11:00:15+02:00       [WARNING] COMPILATION WARNING : 
2024-06-11T11:00:15+02:00       [INFO] -------------------------------------------------------------
2024-06-11T11:00:15+02:00       [WARNING] bootstrap class path not set in conjunction with -source 8
2024-06-11T11:00:15+02:00       [INFO] 1 warning
2024-06-11T11:00:15+02:00       [INFO] -------------------------------------------------------------
2024-06-11T11:00:15+02:00       [INFO] -------------------------------------------------------------
2024-06-11T11:00:15+02:00       [ERROR] COMPILATION ERROR : 
2024-06-11T11:00:15+02:00       [INFO] -------------------------------------------------------------
2024-06-11T11:00:15+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[4,1] package dev.snowdrop.buildpack does not exist
2024-06-11T11:00:15+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[5,1] package dev.snowdrop.buildpack.config does not exist
2024-06-11T11:00:15+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[6,1] package dev.snowdrop.buildpack.docker does not exist
2024-06-11T11:00:15+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[21,33] cannot find symbol
2024-06-11T11:00:15+02:00         symbol:   class SystemLogger
2024-06-11T11:00:15+02:00         location: class dev.snowdrop.pack
2024-06-11T11:00:15+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[19,38] cannot find symbol
2024-06-11T11:00:15+02:00         symbol:   class ImageReference
2024-06-11T11:00:15+02:00         location: class dev.snowdrop.pack
2024-06-11T11:00:15+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[18,39] cannot find symbol
2024-06-11T11:00:15+02:00         symbol:   class ImageReference
2024-06-11T11:00:15+02:00         location: class dev.snowdrop.pack
2024-06-11T11:00:15+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[17,24] cannot find symbol
2024-06-11T11:00:15+02:00         symbol:   variable BuildConfig
2024-06-11T11:00:15+02:00         location: class dev.snowdrop.pack
2024-06-11T11:00:15+02:00       [INFO] 7 errors 
2024-06-11T11:00:15+02:00       [INFO] -------------------------------------------------------------
2024-06-11T11:00:15+02:00       [INFO] ------------------------------------------------------------------------
2024-06-11T11:00:15+02:00       [INFO] BUILD FAILURE
2024-06-11T11:00:15+02:00       [INFO] ------------------------------------------------------------------------
2024-06-11T11:00:16+02:00       [INFO] Total time:  02:16 min
2024-06-11T11:00:16+02:00       [INFO] Finished at: 2024-06-11T09:00:15Z
2024-06-11T11:00:16+02:00       [INFO] ------------------------------------------------------------------------
2024-06-11T11:00:16+02:00       [ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.12.1:compile (default-compile) on project quarkus-hello: Compilation failure: Compilation failure: 
2024-06-11T11:00:16+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[4,1] package dev.snowdrop.buildpack does not exist
2024-06-11T11:00:16+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[5,1] package dev.snowdrop.buildpack.config does not exist
2024-06-11T11:00:16+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[6,1] package dev.snowdrop.buildpack.docker does not exist
2024-06-11T11:00:16+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[21,33] cannot find symbol
2024-06-11T11:00:16+02:00       [ERROR]   symbol:   class SystemLogger
2024-06-11T11:00:16+02:00       [ERROR]   location: class dev.snowdrop.pack
2024-06-11T11:00:16+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[19,38] cannot find symbol
2024-06-11T11:00:16+02:00       [ERROR]   symbol:   class ImageReference
2024-06-11T11:00:16+02:00       [ERROR]   location: class dev.snowdrop.pack
2024-06-11T11:00:16+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[18,39] cannot find symbol
2024-06-11T11:00:16+02:00       [ERROR]   symbol:   class ImageReference
2024-06-11T11:00:16+02:00       [ERROR]   location: class dev.snowdrop.pack
2024-06-11T11:00:16+02:00       [ERROR] /workspace/src/main/java/dev/snowdrop/pack.java:[17,24] cannot find symbol
2024-06-11T11:00:16+02:00       [ERROR]   symbol:   variable BuildConfig
2024-06-11T11:00:16+02:00       [ERROR]   location: class dev.snowdrop.pack
2024-06-11T11:00:16+02:00       [ERROR] -> [Help 1]
2024-06-11T11:00:16+02:00       [ERROR] 
2024-06-11T11:00:16+02:00       [ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
2024-06-11T11:00:16+02:00       [ERROR] Re-run Maven using the -X switch to enable full debug logging.
2024-06-11T11:00:16+02:00       [ERROR] 
2024-06-11T11:00:16+02:00       [ERROR] For more information about the errors and possible solutions, please read the following articles:
2024-06-11T11:00:16+02:00       [ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
2024-06-11T11:00:16+02:00 unable to invoke layer creator
2024-06-11T11:00:16+02:00 unable to contribute application layer
2024-06-11T11:00:16+02:00 error running build
2024-06-11T11:00:16+02:00 exit status 1
2024-06-11T11:00:16+02:00       Timer: Builder ran for 2m32.471688152s and ended at 2024-06-11T09:00:16Z
2024-06-11T11:00:16+02:00 ERROR: failed to build: exit status 1
[main] INFO dev.snowdrop.buildpack.lifecycle.phases.Extender - Buildpack extender container complete, with exit code 51
[main] INFO dev.snowdrop.buildpack.lifecycle.LifecyclePhaseFactory - - tidying up the build volumes
[main] INFO dev.snowdrop.buildpack.lifecycle.LifecyclePhaseFactory - - build volumes tidied up
```

**Comment by BarDweller** [comment] 2024-10-12 01:59
Closing as still unable to recreate.

**Closed by BarDweller** 2024-10-12 01:59 UTC
